#!/usr/bin/env python3
"""Turn real ttymidi captures into a C header for the end-to-end parser tests.

Reads the two dumps under tests/fixtures/ (captured on a Raspberry Pi):

  - dump_serial_print.txt : ttymidi -p output, i.e. the raw serial bytes as
    tab-separated hex. This is the exact wire data, used verbatim.
  - dump_verbose.txt      : ttymidi -v output, i.e. ttymidi's own decoded log
    ("Serial 0xb0 Controller change  000 017 001"). We rebuild the 3-byte
    message each line represents, so the test can re-parse the real sequence.

Emits tests/dump_fixtures.h with the two byte streams plus the independently
counted message composition, so the test's expectations don't come from our
own parser. Run from the repo root: python3 tests/gen_dump_fixtures.py
"""

from __future__ import annotations

from collections import Counter
from pathlib import Path

HERE = Path(__file__).resolve().parent
FIXTURES = HERE / "fixtures"


def load_serial_print() -> list[int]:
    """Raw wire bytes from `ttymidi -p` (tab-separated hex, banner on line 1)."""
    lines = (FIXTURES / "dump_serial_print.txt").read_text().splitlines()
    toks = [t for line in lines for t in line.split("\t") if _is_hex(t)]
    return [int(t, 16) for t in toks]


def load_verbose() -> list[int]:
    """Rebuild the raw bytes behind each decoded `ttymidi -v` line."""
    out: list[int] = []
    for line in (FIXTURES / "dump_verbose.txt").read_text().splitlines():
        f = line.split()
        # e.g. ['Serial', '0xb0', 'Controller', 'change', '000', '017', '001']
        if len(f) < 5 or not f[1].startswith("0x"):
            continue  # skip banner / shutdown lines
        op = int(f[1], 16)
        ch, p1, p2 = (int(x) for x in f[-3:])
        out += [op | ch, p1, p2]  # status byte carries the channel in its low nibble
    return out


def _is_hex(tok: str) -> bool:
    tok = tok.strip()
    try:
        int(tok, 16)
    except ValueError:
        return False
    return bool(tok)


def compose(stream: list[int]) -> Counter[int]:
    """Count messages by status nibble (assumes clean 3-byte-per-message data)."""
    return Counter(stream[i] & 0xF0 for i in range(0, len(stream), 3))


def emit_array(name: str, data: list[int]) -> str:
    rows = [
        ", ".join(f"0x{b:02x}" for b in data[i : i + 12]) for i in range(0, len(data), 12)
    ]
    body = ",\n    ".join(rows)
    return (
        f"static const unsigned char {name}[] = {{\n    {body}\n}};\n"
        f"static const int {name}_len = {len(data)};\n"
    )


def main() -> None:
    serial = load_serial_print()
    verbose = load_verbose()
    sc, vc = compose(serial), compose(verbose)

    lines = [
        "/* Auto-generated by tests/gen_dump_fixtures.py from real Raspberry Pi",
        "   captures in tests/fixtures/. Do not edit by hand. */",
        "#ifndef DUMP_FIXTURES_H",
        "#define DUMP_FIXTURES_H",
        "",
        "/* Raw serial bytes captured with `ttymidi -p`. */",
        emit_array("serial_print_bytes", serial),
        f"#define SERIAL_PRINT_MSGS {len(serial) // 3}",
        f"#define SERIAL_PRINT_CC {sc[0xB0]}",
        f"#define SERIAL_PRINT_NOTE_ON {sc[0x90]}",
        f"#define SERIAL_PRINT_NOTE_OFF {sc[0x80]}",
        "",
        "/* Bytes rebuilt from ttymidi's own `-v` decoded log. */",
        emit_array("verbose_bytes", verbose),
        f"#define VERBOSE_MSGS {len(verbose) // 3}",
        f"#define VERBOSE_CC {vc[0xB0]}",
        f"#define VERBOSE_NOTE_ON {vc[0x90]}",
        f"#define VERBOSE_NOTE_OFF {vc[0x80]}",
        "",
        "#endif /* DUMP_FIXTURES_H */",
    ]
    (HERE / "dump_fixtures.h").write_text("\n".join(lines) + "\n")
    print(f"serial_print: {len(serial)} bytes, {len(serial)//3} msgs {dict(sc)}")
    print(f"verbose:      {len(verbose)} bytes, {len(verbose)//3} msgs {dict(vc)}")


if __name__ == "__main__":
    main()
