"""Minimal type stubs for the python-rtmidi API used by these tests.

python-rtmidi is a C extension with no bundled stubs; this declares just the
surface the harness touches so basedpyright can check our calls.
"""

from collections.abc import Sequence

class MidiBase:
    def get_ports(self) -> list[str]: ...
    def open_port(self, port: int = ...) -> object: ...
    def close_port(self) -> None: ...
    def delete(self) -> None: ...

class MidiIn(MidiBase):
    def ignore_types(
        self, sysex: bool = ..., timing: bool = ..., active_sense: bool = ...
    ) -> None: ...
    def get_message(self) -> tuple[list[int], float] | None: ...

class MidiOut(MidiBase):
    def send_message(self, message: Sequence[int]) -> None: ...
